"""add_word

Revision ID: 0aa8a2de2a12
Revises: 63d2296e190a
Create Date: 2025-11-16 01:51:42.116856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0aa8a2de2a12"
down_revision: Union[str, Sequence[str], None] = "63d2296e190a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("addresses", sa.Column("address", sa.String(), nullable=False))
    op.drop_column("addresses", "addres")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column("addres", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("addresses", "address")
    # ### end Alembic commands ###
